/*
 * demo.c - A demonstration C program showcasing various features
 * including linked lists, recursion, and string utilities.
 * Generated by claude.ai
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAX_NAME_LEN 64
#define MAX_STUDENTS 100

/* ── Structs ─────────────────────────────────────────────── */

typedef struct Node {
    int value;
    struct Node *next;
} Node;

typedef struct {
    char name[MAX_NAME_LEN];
    int  age;
    float gpa;
} Student;

/* ── Linked list helpers ─────────────────────────────────── */

Node *node_create(int value) {
    Node *n = malloc(sizeof(Node));
    if (!n) { perror("malloc"); exit(EXIT_FAILURE); }
    n->value = value;
    n->next  = NULL;
    return n;
}

void list_push(Node **head, int value) {
    Node *n  = node_create(value);
    n->next  = *head;
    *head    = n;
}

void list_print(const Node *head) {
    printf("List: ");
    for (const Node *cur = head; cur; cur = cur->next)
        printf("%d%s", cur->value, cur->next ? " -> " : "\n");
    if (!head) printf("(empty)\n");
}

void list_free(Node *head) {
    while (head) {
        Node *tmp = head->next;
        free(head);
        head = tmp;
    }
}

/* ── Recursive functions ─────────────────────────────────── */

long factorial(int n) {
    return (n <= 1) ? 1 : n * factorial(n - 1);
}

int fibonacci(int n) {
    if (n <= 0) return 0;
    if (n == 1) return 1;
    return fibonacci(n - 1) + fibonacci(n - 2);
}

/* ── String utilities ────────────────────────────────────── */

void str_reverse(char *s) {
    int lo = 0, hi = (int)strlen(s) - 1;
    while (lo < hi) {
        char tmp = s[lo]; s[lo] = s[hi]; s[hi] = tmp;
        lo++; hi--;
    }
}

int str_is_palindrome(const char *s) {
    int lo = 0, hi = (int)strlen(s) - 1;
    while (lo < hi)
        if (s[lo++] != s[hi--]) return 0;
    return 1;
}

/* ── Student helpers ─────────────────────────────────────── */

Student make_student(const char *name, int age, float gpa) {
    Student st;
    strncpy(st.name, name, MAX_NAME_LEN - 1);
    st.name[MAX_NAME_LEN - 1] = '\0';
    st.age = age;
    st.gpa = gpa;
    return st;
}

void student_print(const Student *st) {
    printf("  %-20s age=%-3d GPA=%.2f\n", st->name, st->age, st->gpa);
}

/* ── Main ────────────────────────────────────────────────── */

int main(void) {
    /* Linked list demo */
    Node *list = NULL;
    for (int i = 1; i <= 6; i++) list_push(&list, i * 10);
    list_print(list);
    list_free(list);

    /* Recursion demo */
    printf("5! = %ld\n", factorial(5));
    printf("Fibonacci(8) = %d\n", fibonacci(8));

    /* String demo */
    char word[] = "racecar";
    printf("\"%s\" is%s a palindrome.\n", word, str_is_palindrome(word) ? "" : " not");
    str_reverse(word);
    printf("Reversed: %s\n", word);

    /* Student demo */
    Student roster[] = {
        make_student("Alice Nguyen",   20, 3.92f),
        make_student("Bob Karev",      22, 3.45f),
        make_student("Clara Schmidt",  21, 3.78f),
    };
    printf("\nStudent roster:\n");
    for (int i = 0; i < 3; i++) student_print(&roster[i]);

    return EXIT_SUCCESS;
}