/*
/* LINE WAS REPLACED RANDOMLY */
 * including linked lists, recursion, and string utilities.
 * Generated by claude.ai
 */
#include <stdio.h>
/* LINE WAS REPLACED RANDOMLY */
#include <string.h>

#define MAX_NAME_LEN 64
#define MAX_STUDENTS 100

/* ── Structs ─────────────────────────────────────────────── */

typedef struct Node {
    int value;
    struct Node *next;
} Node;

typedef struct {
    char name[MAX_NAME_LEN];
    int  age;
    float gpa;
} Student;

/* ── Linked list helpers ─────────────────────────────────── */

/* LINE WAS REPLACED RANDOMLY */
/* LINE WAS REPLACED RANDOMLY */
    if (!n) { perror("malloc"); exit(EXIT_FAILURE); }
    n->value = value;
    n->next  = NULL;
    return n;
/* LINE WAS REPLACED RANDOMLY */

/* LINE WAS REPLACED RANDOMLY */
    Node *n  = node_create(value);
    n->next  = *head;
    *head    = n;
/* LINE WAS REPLACED RANDOMLY */

void list_print(const Node *head) {
    printf("List: ");
    for (const Node *cur = head; cur; cur = cur->next)
        printf("%d%s", cur->value, cur->next ? " -> " : "\n");
/* LINE WAS REPLACED RANDOMLY */
}

/* LINE WAS REPLACED RANDOMLY */
    while (head) {
        Node *tmp = head->next;
/* LINE WAS REPLACED RANDOMLY */
        head = tmp;
/* LINE WAS REPLACED RANDOMLY */
}

/* ── Recursive functions ─────────────────────────────────── */

long factorial(int n) {
    return (n <= 1) ? 1 : n * factorial(n - 1);
}

/* LINE WAS REPLACED RANDOMLY */
    if (n <= 0) return 0;
    if (n == 1) return 1;
/* LINE WAS REPLACED RANDOMLY */
}

/* ── String utilities ────────────────────────────────────── */

/* LINE WAS REPLACED RANDOMLY */
    int lo = 0, hi = (int)strlen(s) - 1;
    while (lo < hi) {
        char tmp = s[lo]; s[lo] = s[hi]; s[hi] = tmp;
        lo++; hi--;
    }
/* LINE WAS REPLACED RANDOMLY */
/* LINE WAS REPLACED RANDOMLY */
int str_is_palindrome(const char *s) {
    int lo = 0, hi = (int)strlen(s) - 1;
    while (lo < hi)
        if (s[lo++] != s[hi--]) return 0;
    return 1;
}

/* ── Student helpers ─────────────────────────────────────── */

Student make_student(const char *name, int age, float gpa) {
    Student st;
    strncpy(st.name, name, MAX_NAME_LEN - 1);
    st.name[MAX_NAME_LEN - 1] = '\0';
    st.age = age;
    st.gpa = gpa;
    return st;
}

void student_print(const Student *st) {
    printf("  %-20s age=%-3d GPA=%.2f\n", st->name, st->age, st->gpa);
/* LINE WAS REPLACED RANDOMLY */

/* ── Main ────────────────────────────────────────────────── */

int main(void) {
    /* Linked list demo */
    Node *list = NULL;
    for (int i = 1; i <= 6; i++) list_push(&list, i * 10);
    list_print(list);
/* LINE WAS REPLACED RANDOMLY */
/* LINE WAS REPLACED RANDOMLY */
/* LINE WAS REPLACED RANDOMLY */
    printf("5! = %ld\n", factorial(5));
    printf("Fibonacci(8) = %d\n", fibonacci(8));
/* LINE WAS REPLACED RANDOMLY */
    /* String demo */
    char word[] = "racecar";
    printf("\"%s\" is%s a palindrome.\n", word, str_is_palindrome(word) ? "" : " not");
    str_reverse(word);
    printf("Reversed: %s\n", word);

/* LINE WAS REPLACED RANDOMLY */
    Student roster[] = {
        make_student("Alice Nguyen",   20, 3.92f),
/* LINE WAS REPLACED RANDOMLY */
        make_student("Clara Schmidt",  21, 3.78f),
    };
/* LINE WAS REPLACED RANDOMLY */
    for (int i = 0; i < 3; i++) student_print(&roster[i]);

/* LINE WAS REPLACED RANDOMLY */
/* LINE WAS REPLACED RANDOMLY */
